module Bovespa(
  
) where
  
import ECS.Model.SecuritiesTypes





data SecurityType = Stp{abbrev :: String, desc:: String} deriving (Show)

fromAbbrev:: (String a, SecurityType s) => a -> s

fromAbbrev abr = case abr of
     "ON"  -> Stp "ON"  "AÇÕES ORDINÁRIAS NOMINATIVAS"
     "PNA" -> Stp "PNA" " AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE A"
     "PNB" -> Stp "PNB" "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE B"
     "PNC" -> Stp "PNC" " AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE C"
     "PND" -> Stp "PND" " AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE D"



tradeTypeFromCode :: Int -> TradeType
tradeTypeFromCode 10 = Spot
tradeTypeFromCode 12 = OptBuyExc
tradeTypeFromCode 13 = OptSellExc
tradeTypeFromCode 17 = Auction
tradeTypeFromCode 20 = Fraction
tradeTypeFromCode 30 = Term
tradeTypeFromCode 50 = FutureRetainedEarnings
tradeTypeFromCode 60 = FutureContinuousMov
tradeTypeFromCode 70 = OptBuy
tradeTypeFromCode 80 = OptSell
tradeTypeFromCode _  = error "Invalid trade type"


bdiFromCode:: Int -> BDI
bdiFromCode 2 = StandardIssue
bdiFromCode 6 = Bankrupt
bdiFromCode _ = error "Unknow Code"

              --02 LOTE PADRÃO
--06 CONCORDATÁRIAS
--10 DIREITOS E RECIBOS
--12 FUNDOS IMOBILIÁRIOS

--14 CERTIFIC. INVESTIMENTO / DEBÊNTURES / TÍTULOS DIVIDA PÚBLICA 18 OBRIGAÇÕES
--22 BÔNUS (PRIVADOS)
--26 APÓLICES / BÔNUS / TÍTULOS PÚBLICOS
--32 EXERCÍCIO DE OPÇÕES DE COMPRA DE ÍNDICE
--33 EXERCÍCIO DE OPÇÕES DE VENDA DE ÍNDICE
--38 EXERCÍCIO DE OPÇÕES DE COMPRA 42 EXERCÍCIO DE OPÇÕES DE VENDA 46 LEILÃO DE TÍTULOS NÃO COTADOS
--48 LEILÃO
--50 LEILÃO
--51 LEILÃO
--52 LEILÃO
--53 LEILÃO
--54 LEILÃO DE AÇÕES EM MORA
--56 VENDAS POR ALVARÁ JUDICIAL 58 OUTROS
--60 PERMUTA POR AÇÕES
--61 META
--62 TERMO
--66 DEBÊNTURES COM DATA DE VENCIMENTO ATÉ 3 ANOS
--68 DEBÊNTURES COM DATA DE VENCIMENTO MAIOR QUE 3 ANOS
--70 FUTURO COM MOVIMENTAÇÃO CONTÍNUA
--71 FUTURO COM RETENÇÃO DE GANHO
--74 OPÇÕES DE COMPRA DE ÍNDICES
--75 OPÇÕES DE VENDA DE ÍNDICES
--78 OPÇÕES DE COMPRA
--82 OPÇÕES DE VENDA
---83 DEBÊNTURES E NOTAS PROMISSÓRIAS
--96 FRACIONÁRIO 99 TOTAL GERAL
       

--data BovTradeType Int String = Spot 010 "VISTA" | ExOptBuy 012 "EXERCÍCIO DE OPÇÕES DE COMPRA" | ExOptSell 013 "EXERCÍCIO DE OPÇÕES DE VENDA" | Auction 017 "LEILÃO" | Fraction 020 "FRACIONÁRIO" |
--Term 030 "TERMO" |  FutureRetainedEarnings 050 "FUTURO COM RETENÇÃO DE GANHO" | FutureContinuous 060 "FUTURO COM MOVIMENTAÇÃO CONTÍNUA" OptBuy 070 "OPÇÕES DE COMPRA" | OptSell 080 "OPÇÕES DE VENDA"


data CODBDI Int String =
  CODBDI 02 "LOTE PADRÃO"
  CODBDI 06 "CONCORDATÁRIAS"
  CODBDI 10 "DIREITOS E RECIBOS"
  CODBDI 12 "FUNDOS IMOBILIÁRIOS"
  CODBDI 14 "CERTIFIC. INVESTIMENTO / DEBÊNTURES / TÍTULOS DIVIDA PÚBLICA 18 OBRIGAÇÕES"
  CODBDI 22 "BÔNUS (PRIVADOS)"
  CODBDI 26 "APÓLICES / BÔNUS / TÍTULOS PÚBLICOS"
  CODBDI 32 "EXERCÍCIO DE OPÇÕES DE COMPRA DE ÍNDICE"
  CODBDI 33 "EXERCÍCIO DE OPÇÕES DE VENDA DE ÍNDICE"
  CODBDI 38 "EXERCÍCIO DE OPÇÕES DE COMPRA"
  CODBDI 42 "EXERCÍCIO DE OPÇÕES DE VENDA"
  CODBDI 46 "LEILÃO DE TÍTULOS NÃO COTADOS"
  CODBDI 48 "LEILÃO"
  CODBDI 50 "LEILÃO"
  
51 LEILÃO
52 LEILÃO
53 LEILÃO
54 LEILÃO DE AÇÕES EM MORA
56 VENDAS POR ALVARÁ JUDICIAL 58 OUTROS
60 PERMUTA POR AÇÕES
61 META
62 TERMO
66 DEBÊNTURES COM DATA DE VENCIMENTO ATÉ 3 ANOS
68 DEBÊNTURES COM DATA DE VENCIMENTO MAIOR QUE 3 ANOS
70 FUTURO COM MOVIMENTAÇÃO CONTÍNUA
71 FUTURO COM RETENÇÃO DE GANHO
74 OPÇÕES DE COMPRA DE ÍNDICES
75 OPÇÕES DE VENDA DE ÍNDICES
78 OPÇÕES DE COMPRA
82 OPÇÕES DE VENDA
83 DEBÊNTURES E NOTAS PROMISSÓRIAS
96 FRACIONÁRIO 99 TOTAL GERAL
  
